language: python
python: # 3.0 is not supported on Travis CI
    - "3.6"
    - "3.7"
cache: pip
install:
    - pip install ".[tests,nn]"
script:
    - pytest --cov-report term --cov=audlib tests/
env:
    - PYTHONPATH=`pwd`
    - CODECOV_TOKEN="dd757c20-296f-4e7f-bd4f-1ac7a098fea8"
after_success:
    - codecov
